---
title: "Asthma-related health outcomes and air quality in NYC"
output: html_document
---
### Group members:

Jessie Wong (jw3957) (Github: jessiewongus)
Darwin Keung (dk2759) (Github: darwinthebeagle)
Felix Tran (fwt2107) (Github: fwt2107)
Vince Tam (vt2243) (Github: noshame11)

**Motivation:**

Asthma is a major public health concern both in New York City and nationally across the United States. According to CDC's Behaviorial Risk Factor Surveillance System (BRFSS) data in 2012, approximately 1.4 million New York adults and 314,000 children (under the age of 18) reported having asthma. While data has shown that in the last 10 years, annual asthma related deaths have decreased significantly by over 20%, asthma prevalence has been increasing.  

Our motivation for the project is to understand the air quality across the different neighborhoods in New York City, through looking at different pollutants and their levels. There are multiple air exposures both outdoor and indoor that can in combination, exacerbate asthma conditions and prevalence among different groups, particularly vulnerable children and elderly. Our group is interesting in understanding the potential disparities that may exist across different neighborhoods in terms of air pollution distribution and its effects, particularly in neighborhoods with high poverty and low socio-economic status.  

**Related work:**

Research has observed that people living in inner cities like New York, Chicago and Baltimore, had rates of asthma in general and they seemed to have very high rates of hospitalization and emergency room visits.

The urban environment can generate large amounts of environmental pollutants such as PM2.5 which contribute to increase morbidity and morality outcomes such as asthma. A major source of PM2.5 is from burning heating oil for buildings and traffic. Historically rooted inequities places much of this environmental health burder of PM2.5 pollution and asthma on lower income communities. For further infomation on the Environmental Health Impact Assessment of PM2.5 check out this [paper](http://a816-dohbesp.nyc.gov/IndicatorPublic/traffic/index.html) and this neat interactive webpage the New York City Community Health Survey Team put together [here](http://a816-dohbesp.nyc.gov/IndicatorPublic/traffic/index.html). 

While the external city environment plays a role in our health, the home environment is critical as well [The indoor environment and inner-city childhood asthma](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4110514/). Exposure to indoor pollutants and allergens like mold and roach allergen and high Nitrogen dioxide concentrations from poor ventilation of gas stoves and furnaces are some factors linked to asthma as well.

Lastly we should keep in mind the socio-economic factors of asthma. NPR and _All Things Considered_ did a provacatively penned piece ["The City Might Not Be To Blame For High Asthma Rates"](https://www.npr.org/sections/health-shots/2015/01/20/378608279/the-inner-city-might-not-be-to-blame-for-high-asthma-rates) based on 
[Keet et al. (2015)](https://www.jacionline.org/article/S0091-6749%2814%2901676-5/abstract). Dr. Keet and her collaborators found that even more children had asthma in poor suburban and medium sized towns in other regions of the country. Additionally living in the inner city didn't seem to a risk factor at all for having asthma for children outside of the Northeastern states.Inner cities areas have higher burden of asthma conflated with areas of poverty.That is to say poverty is stronger predictive factor than the location you live in, possibily due to more day to day stress and diet factors that contribute to the weathering of your body and your immune system. 

Initial questions: What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?

**Initial questions:**

Our initial questions: 
1) What is the distribution of asthma rates across neighborhoods?
2) What is the relationship between pollution levels and the poverty level of the neighborhood? 
3) How do the rates of asthma-related ED visits, hospitalizations, and deaths between different neighborhoods compare? Are there any indication of disparities?
4) What is the impact of the collective exposure to high levels of all the pollutants in comparison to exposure to them individually?
5) How does the indoor exposure to mold compare to the outdoor pollution exposure and it's effect on asthma?

Our initial questions revolved around the effects of traffic, air quality, and asthma among New York City residents differ across boroughs, income level, years, neighborhoods, and age groups. We found that our data set was missing certain years, so we dropped the time aspect of our analysis. We learned more about indoor quality and added mold as a factor to look at. The traffic data was more of an source of air pollution and not the immediate factor on a causial pathway so we focused more on air pollution than traffic data.

**Process:**

Intial plan analyses/visualizations and outcome

- GIS visualization - neighborhood/census tract visualization of case cluster.
  - Had issues matching geocodes and neighbhood locations. Wish to return to this someday, but need more knowledge in GIS and R to make this happen.
  
- Barplot of health outcomes (attributable deaths, asthma ED visits, and hospitalizations) vs neighborhood demographics
  - Made a shiny object and repo for this.
  
- Spaghetti plot displaying rate of asthma-related ED visits over time by borough
  - Time was not continious, there isn't data from 2008, and the cases were grouped into two time periods, 2005 to 2007 and 2009 to 2011. Made this a shiny bargraph instead.
  
- Graph displaying how different age groups (children, adults, elderly) may be affected differently by air quality in health outcomes
  - this last plot was merged into shiny bargraph as a age group filter

----------

**Data Information:**

All the datafiles that we used on the project can be found [here](https://github.com/darwinthebeagle/asthma_nyc/tree/master/Data) in Github.

The data was obtained from the [NYC Environment & Health Data Portal](http://a816-dohbesp.nyc.gov/IndicatorPublic/PublicTracking.aspx) and the [NYC OpenData](https://data.cityofnewyork.us/Environment/Air-Quality/c3uy-2p5r/data).  

NYC Environment & Health Data Portal: We extracted data regarding the air pollutant levels (2005 and 2013) and asthma-related health outcomes, including deaths, hospitalization, and emergency department visits (2005-2007, 2009-2011). 

NYC OpenData: We extracted data regarding mold reported in homes and poverty percentages.

The New York City neighborhood boundaries were defined by the [United Hospital Fund Neighorhood Index](http://a816-dohbesp.nyc.gov/IndicatorPublic/EPHTPDF/uhf42.pdf). There are a total of 42 neighorboods across the 5 boroughs—Bronx, Staten Island, Queens, Manhattan, and Brooklyn.   

Cleaning:
After loading the datasets we cleaned it, through filtering for specific years that were the most recent and matched across the different exposures and outcomes for merge. We also converted variables to different forms to manipulate for our analysis including to factors and numericals. Our data cleaning github file can be found [here](https://github.com/darwinthebeagle/asthma_nyc/blob/master/Data_cleaning.Rmd) with the dataset loading and initial cleaning. However additional changes and methods of using the data for our analyses can be found in the links below.

----------

**Exploratory analysis:** 

Air Pollutant Plotly
[Github file](https://github.com/darwinthebeagle/asthma_nyc/blob/master/plotly.Rmd)

We generated the density plots across the different air pollutants by boroughs. Originally we had planned on mapping the change over time in air quality across the different boroughs to visualize trends, including how pollution levels have changed over time within each borough and comparing the levels within boroughs. However our dataset had only provided the pollutant levels for two years. Instead, using the density plots, we are able to examine the concentration of values within each borough and the distribution based on width across the x-axis. Based on the plots, we are looking to see if there are patterns in air pollution across different boroughs. For example, whether high densities and low densities are found within the same boroughs for different pollutants. 

Mold Plotly
[Github file](https://github.com/darwinthebeagle/asthma_nyc/blob/master/mold_plotly.Rmd)

In addition to outdoor air quality that may trigger and exacerbate asthma, we wanted to explore potential indoor exposures that are linked to asthma. Mold can trigger asthma and affect individuals' ability to control their asthma, particularly if it is within one's home and persists as a constant everday exposure. The data source we located reported the number of mold complaints by NYC neighborhoods. We selected the age-adjusted rates to allow the populations in our analysis to be compared when the age profiles may be potentially quite different.

**Additional analysis:**

Linear Regression
[Github file](https://github.com/darwinthebeagle/asthma_nyc/blob/master/Linear_regression.Rmd)

We ran 2 linear regression models on PM 2.5-attributable asthma ED rates for
adults and children by neighborhood poverty and PM 2.5 air levels. PM 
2.5-attributable asthma ED rates were age-adjusted rates per 100,000 adults or 
children depending on the model for the timespan 2009-2011. PM 2.5 air levels
were measured as the average of the yearly mean micrograms of PM 2.5 per cubic
meter of air for the years 2009, 2010, and 2011. Neighborhood poverty was
measured as the proportion of people living in poverty in a given neighborhood. 
Neighborhoods are defined as [such](https://www.health.ny.gov/statistics/cancer/registry/appendix/neighborhoods.htm). 
We calculated the beta coefficients for PM 2.5 air levels and neighborhood 
poverty, 95% confidence intervals, and p-values for t-tests at a 5% significance
level of each estimated coefficient after controlling for the other coefficient. 

----------

**Discussion** 

Air Pollutants: 
Based on our density plots found in the Pollution Density tab, we see varying distribution of the different outdoor air pollutants. Among the different boroughs, Queens and Staten Island remain on the lower end of the concentration levels for all 5 pollutants examined. Manhattan had the widest distribution of concentration levels, illustrating that there is a wider spectrum of high pollutation levels in certain neighborhoods and low levels in others. Bronx and Brooklyn's pollution levels stayed in the middle ranges in comparison to the other boroughs, however, there is significant peaking for certain pollutants, including Benzene for Bronx. We expected there the be a more consistent and defined pattern across the different pollutants across boroughs, of boroughs with high and low densities. However this may be attributed to the manner that the pollutant is emitted and the sources. Through exploring the data, we also recognized that there is significant within borough differences and gaps, where certain regions of the borough experience very high densities of pollution and others experience very low, which is surprising considering that they are in close proximity. 

Mold Complaints in Homes: 
For the data on mold complaints in homes, there were 9 neighborhoods with unavailable data. However 3 out of the 5 neighborhoods with the highest mold reports were located in Bronx. We took into account that since the data is based on self-report, there may be potentially cases that go unreported. It is possible that if there is reporting bias across neighborhoods in the different boroughs, this may underestimate the differences and level of mold in homes. 

Asthma-Related Health Outcomes: 
There are neigborhood differences in the rates of asthma-related emergency department visits, hospitalizations, and deaths. From the 2005-2007 and 2009-2011 data, we consistently found that Bronx had the highest rates of emergency department visits and hospitalizaations for adults and children (under the age of 18), where it is approximately double the rate of the other boroughs. In addition to comparison between boroughs, differences and similarities in outcomes within boroughs were also evaluated. When we stratified within neighborhoods belonging to the same boroughs, there were significant disparities found. For emergency department visits in Manhattan (2005-2007), East Harlem had a rate of 143.9 per 100,000 adults and Central Harlem had a rate of 156.1 per 100,000 adults compared to the rest of Manhattan that had a rate ranging from 8.5 to 46. We observed similar gaps across the other boroughs as well. This reinforces a similar observation in air pollutants, where there is wihin borough differences and gaps that must be addressed. While the group expected differences in asthma-related health outcomes between different boroughs, we did not expect such large ones within boroughs.     

Linear Regression:
After visualizing the distribution pollutants across neighborhoods, a linear regression is performed on PM 2.5-attributable ED visits among NYC neighborhoods by PM 2.5 levels and neighborhood poverty. For both child and adult rates of ED vists, levels of neighborhood PM 2.5 air pollution do not appear to have a significant effect. Rather, neighborhood poverty is strongly associated with ED visits. For every 1% increase in the proportion of people living in poverty in a particular neighborhood, that neighborhood on average experiences an increase of 3.46 ED visits for PM 2.5-attributable asthma per every 100,000 adults and an increase of 5.66 ED visits for PM 2.5-attributable asthma per every 100,000 children. 

