---
title: "Linear_regression"
author: "Felix Tran"
date: "December 2, 2018"
output: html_document
---

This file runs a linear regression on PM 2.5-attributable ED visits among NYC
neighborhoods by PM 2.5 levels and neighborhood poverty.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(modelr)
library(mgcv)
library(purrr)
library(readr)
```

# Cleaning the data

```{r}
poverty_df <- readr::read_csv('./Data/pm_and_poverty_09-13.csv') %>% 
  janitor::clean_names() %>% 
  filter(str_detect(geo_type_name, "UHF") == T) %>% 
  filter(measure == "Percent") %>%
  filter(name == "Poverty") %>% 
  mutate(geography_id = as.integer(geo_entity_id)) %>% 
  rename(poverty_rate = data_value) %>% 
  select(geography_id, poverty_rate)

pm_df <- readr::read_csv('./Data/pm_and_poverty_09-13.csv') %>% 
  janitor::clean_names() %>% 
  filter(str_detect(geo_type_name, "UHF") == T) %>% 
  filter(measure == "Mean") %>%
  filter(str_detect(name, "PM") == T) %>% 
  mutate(geography_id = as.integer(geo_entity_id)) %>% 
  group_by(geography_id) %>% 
  summarize(pm_level = round(mean(data_value), digits = 3))

asthma_df <- readr::read_csv('./Data/nyc_asthma_cleaned.csv') %>% 
  janitor::clean_names() %>% 
  filter(str_detect(geo_type_name, "UHF") == T) %>% 
  filter(str_detect(name, "PM2.5-Attributable Asthma ED") == T) %>% 
  filter(year_description == '2009-2011') %>% 
  rename(geography_id = geo_entity_id) %>% 
  distinct() %>% 
  inner_join(., poverty_df, by = "geography_id") %>% 
  inner_join(., pm_df, by = "geography_id") %>% 
  select(-c(indicator_data_id, indicator_id, name, geo_type_name, 
            year_description)) %>% 
  spread(key = measure, value = data_valuemessage) %>% 
  janitor::clean_names() %>% 
  rename(child_rate = rate_children_0_to_17_yrs_old,
         adult_rate = rate_18_yrs_and_older)
```

```{r}

```

